version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi-app
    command: uvicorn api.main:app --host 0.0.0.0 --port 8001 
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    networks:
      - fastapi-network
  
  worker:
    build: .
    container_name: celery-worker
    command: celery -A api.worker.celery worker -l INFO  
    depends_on:
      - fastapi
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - fastapi-network

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi-network

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge

volumes:
  postgres_data:
